[package]
name = "BFT-test"
version = "0.1.0"
authors = ["Eason Gao <kaoimin@qq.com>"]
edition = "2018"

[dependencies]
criterion = "0.2"
crossbeam = "0.7"
rand = "0.5.5"
lru-cache = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rusqlite = "0.17"
time = "0.1"
